# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\dialog\notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogNotification(object):
    def setupUi(self, DialogNotification):
        DialogNotification.setObjectName("DialogNotification")
        DialogNotification.resize(346, 152)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogNotification.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNotification)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_text = QtWidgets.QLabel(DialogNotification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_main_text.sizePolicy().hasHeightForWidth())
        self.label_main_text.setSizePolicy(sizePolicy)
        self.label_main_text.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_text.setWordWrap(True)
        self.label_main_text.setObjectName("label_main_text")
        self.verticalLayout.addWidget(self.label_main_text)
        self.frame_button = QtWidgets.QFrame(DialogNotification)
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_button)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_ok.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.verticalLayout.addWidget(self.frame_button)

        self.retranslateUi(DialogNotification)
        QtCore.QMetaObject.connectSlotsByName(DialogNotification)

    def retranslateUi(self, DialogNotification):
        _translate = QtCore.QCoreApplication.translate
        DialogNotification.setWindowTitle(_translate("DialogNotification", "Уведомление"))
        self.label_main_text.setText(_translate("DialogNotification", "Текст сообщения"))
        self.pushButton_ok.setText(_translate("DialogNotification", "Ок"))
import icons_rc
