# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\dialog\choice_yes_no.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogYesNo(object):
    def setupUi(self, DialogYesNo):
        DialogYesNo.setObjectName("DialogYesNo")
        DialogYesNo.resize(319, 139)
        DialogYesNo.setFocusPolicy(QtCore.Qt.NoFocus)
        DialogYesNo.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogYesNo.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DialogYesNo)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_button = QtWidgets.QFrame(DialogYesNo)
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_button)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_yes = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_yes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_yes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout.addWidget(self.pushButton_yes)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_no = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_no.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_no.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout.addWidget(self.pushButton_no)
        self.gridLayout.addWidget(self.frame_button, 2, 0, 1, 3, QtCore.Qt.AlignBottom)
        self.label_main_text = QtWidgets.QLabel(DialogYesNo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_main_text.sizePolicy().hasHeightForWidth())
        self.label_main_text.setSizePolicy(sizePolicy)
        self.label_main_text.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_text.setWordWrap(True)
        self.label_main_text.setObjectName("label_main_text")
        self.gridLayout.addWidget(self.label_main_text, 1, 0, 1, 1)

        self.retranslateUi(DialogYesNo)
        QtCore.QMetaObject.connectSlotsByName(DialogYesNo)

    def retranslateUi(self, DialogYesNo):
        _translate = QtCore.QCoreApplication.translate
        DialogYesNo.setWindowTitle(_translate("DialogYesNo", "Подтверждение"))
        self.pushButton_yes.setText(_translate("DialogYesNo", "Да"))
        self.pushButton_no.setText(_translate("DialogYesNo", "Нет"))
        self.label_main_text.setText(_translate("DialogYesNo", "Текст сообщения"))
import icons_rc
