# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLogin(object):
    def setupUi(self, DialogLogin):
        DialogLogin.setObjectName("DialogLogin")
        DialogLogin.resize(395, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/users/administrator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogLogin.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DialogLogin)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_window = QtWidgets.QFrame(DialogLogin)
        self.frame_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_window)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_login = QtWidgets.QLineEdit(self.frame_window)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.lineEdit_passsword = QtWidgets.QLineEdit(self.frame_window)
        self.lineEdit_passsword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passsword.setObjectName("lineEdit_passsword")
        self.verticalLayout.addWidget(self.lineEdit_passsword)
        self.pushButton_login = QtWidgets.QPushButton(self.frame_window)
        self.pushButton_login.setMinimumSize(QtCore.QSize(130, 35))
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_login.setTabletTracking(False)
        self.pushButton_login.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/other/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_login.setIcon(icon1)
        self.pushButton_login.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout.addWidget(self.pushButton_login, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_window)

        self.retranslateUi(DialogLogin)
        QtCore.QMetaObject.connectSlotsByName(DialogLogin)

    def retranslateUi(self, DialogLogin):
        _translate = QtCore.QCoreApplication.translate
        DialogLogin.setWindowTitle(_translate("DialogLogin", "Авторизация"))
        self.lineEdit_login.setPlaceholderText(_translate("DialogLogin", "Логин..."))
        self.lineEdit_passsword.setPlaceholderText(_translate("DialogLogin", "Пароль..."))
        self.pushButton_login.setText(_translate("DialogLogin", "Войти"))
import icons_rc
