# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\user\message.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 180)
        Form.setStyleSheet("QFrame{\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.frame_message = QtWidgets.QFrame(Form)
        self.frame_message.setGeometry(QtCore.QRect(20, 20, 301, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_message.sizePolicy().hasHeightForWidth())
        self.frame_message.setSizePolicy(sizePolicy)
        self.frame_message.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message.setObjectName("frame_message")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_message)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_icon_social_network = QtWidgets.QLabel(self.frame_message)
        self.label_icon_social_network.setMaximumSize(QtCore.QSize(35, 35))
        self.label_icon_social_network.setText("")
        self.label_icon_social_network.setPixmap(QtGui.QPixmap(":/icons/socialNetwork/vk.png"))
        self.label_icon_social_network.setScaledContents(True)
        self.label_icon_social_network.setObjectName("label_icon_social_network")
        self.gridLayout.addWidget(self.label_icon_social_network, 0, 2, 1, 1)
        self.label_date = QtWidgets.QLabel(self.frame_message)
        self.label_date.setObjectName("label_date")
        self.gridLayout.addWidget(self.label_date, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.label_text_message = QtWidgets.QLabel(self.frame_message)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_text_message.sizePolicy().hasHeightForWidth())
        self.label_text_message.setSizePolicy(sizePolicy)
        self.label_text_message.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_text_message.setWordWrap(True)
        self.label_text_message.setObjectName("label_text_message")
        self.gridLayout.addWidget(self.label_text_message, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_date.setText(_translate("Form", "19.02.2024"))
        self.label_text_message.setText(_translate("Form", "TextLabel"))
import icons_rc
