# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\user\user_hisroty_take_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 486)
        Form.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(80, 30, 421, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 221))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_fio = QtWidgets.QLabel(self.frame)
        self.label_fio.setWordWrap(True)
        self.label_fio.setObjectName("label_fio")
        self.verticalLayout.addWidget(self.label_fio)
        self.label_number_group = QtWidgets.QLabel(self.frame)
        self.label_number_group.setWordWrap(True)
        self.label_number_group.setObjectName("label_number_group")
        self.verticalLayout.addWidget(self.label_number_group)
        self.label_student_id_number = QtWidgets.QLabel(self.frame)
        self.label_student_id_number.setWordWrap(True)
        self.label_student_id_number.setObjectName("label_student_id_number")
        self.verticalLayout.addWidget(self.label_student_id_number)
        self.frame_date = QtWidgets.QFrame(self.frame)
        self.frame_date.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_date.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_date.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_date.setObjectName("frame_date")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_date)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_date_take = QtWidgets.QLabel(self.frame_date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_take.sizePolicy().hasHeightForWidth())
        self.label_date_take.setSizePolicy(sizePolicy)
        self.label_date_take.setWordWrap(False)
        self.label_date_take.setObjectName("label_date_take")
        self.horizontalLayout.addWidget(self.label_date_take)
        self.label_how_many_day = QtWidgets.QLabel(self.frame_date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_how_many_day.sizePolicy().hasHeightForWidth())
        self.label_how_many_day.setSizePolicy(sizePolicy)
        self.label_how_many_day.setWordWrap(True)
        self.label_how_many_day.setObjectName("label_how_many_day")
        self.horizontalLayout.addWidget(self.label_how_many_day)
        self.label_date_return = QtWidgets.QLabel(self.frame_date)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date_return.sizePolicy().hasHeightForWidth())
        self.label_date_return.setSizePolicy(sizePolicy)
        self.label_date_return.setWordWrap(True)
        self.label_date_return.setObjectName("label_date_return")
        self.horizontalLayout.addWidget(self.label_date_return)
        self.verticalLayout.addWidget(self.frame_date, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_all_info = QtWidgets.QPushButton(self.frame)
        self.pushButton_all_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_all_info.setIcon(icon)
        self.pushButton_all_info.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_all_info.setObjectName("pushButton_all_info")
        self.verticalLayout.addWidget(self.pushButton_all_info, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_fio.setText(_translate("Form", "FIO"))
        self.label_number_group.setText(_translate("Form", "Номер группы"))
        self.label_student_id_number.setText(_translate("Form", "Студенческий билет"))
        self.label_date_take.setText(_translate("Form", "Была взята 24.01.2020"))
        self.label_how_many_day.setText(_translate("Form", "На 10 дней"))
        self.label_date_return.setText(_translate("Form", "вернул 26.01.2020"))
        self.pushButton_all_info.setText(_translate("Form", "Подробная информация пользователя"))
import icons_rc
