from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEdit(object):
    def setupUi(self, DialogEdit):
        DialogEdit.setObjectName("DialogEdit")
        DialogEdit.resize(400, 280)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogEdit.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEdit)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_main_text = QtWidgets.QLabel(DialogEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_main_text.sizePolicy().hasHeightForWidth())
        self.label_main_text.setSizePolicy(sizePolicy)
        self.label_main_text.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_text.setWordWrap(True)
        self.label_main_text.setObjectName("label_main_text")
        self.verticalLayout.addWidget(self.label_main_text)
        self.frame_button = QtWidgets.QFrame(DialogEdit)
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_button)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.horizontalLayout_2.addWidget(self.pushButton_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addWidget(self.frame_button, 0, QtCore.Qt.AlignBottom)

        self.retranslateUi(DialogEdit)
        QtCore.QMetaObject.connectSlotsByName(DialogEdit)

    def retranslateUi(self, DialogEdit):
        _translate = QtCore.QCoreApplication.translate
        DialogEdit.setWindowTitle(_translate("DialogEdit", "Подтвердите изменение информации"))
        self.label_main_text.setText(_translate("DialogEdit", "Текст"))
        self.pushButton_edit.setText(_translate("DialogEdit", "Изменить"))
        self.pushButton_cancel.setText(_translate("DialogEdit", "Отменить"))
