# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\book\books.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 223)
        Form.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame_book = QtWidgets.QFrame(Form)
        self.frame_book.setGeometry(QtCore.QRect(40, 30, 351, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_book.sizePolicy().hasHeightForWidth())
        self.frame_book.setSizePolicy(sizePolicy)
        self.frame_book.setMinimumSize(QtCore.QSize(321, 141))
        self.frame_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_book.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_book.setObjectName("frame_book")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_book)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_maim_info = QtWidgets.QFrame(self.frame_book)
        self.frame_maim_info.setMinimumSize(QtCore.QSize(50, 100))
        self.frame_maim_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maim_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maim_info.setObjectName("frame_maim_info")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_maim_info)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_name = QtWidgets.QLabel(self.frame_maim_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.verticalLayout.addWidget(self.label_name)
        self.label_author = QtWidgets.QLabel(self.frame_maim_info)
        self.label_author.setObjectName("label_author")
        self.verticalLayout.addWidget(self.label_author)
        self.label_isbn = QtWidgets.QLabel(self.frame_maim_info)
        self.label_isbn.setObjectName("label_isbn")
        self.verticalLayout.addWidget(self.label_isbn)
        self.label_year_publication = QtWidgets.QLabel(self.frame_maim_info)
        self.label_year_publication.setObjectName("label_year_publication")
        self.verticalLayout.addWidget(self.label_year_publication)
        self.label_all_quantity = QtWidgets.QLabel(self.frame_maim_info)
        self.label_all_quantity.setObjectName("label_all_quantity")
        self.verticalLayout.addWidget(self.label_all_quantity)
        self.label_current_quantity = QtWidgets.QLabel(self.frame_maim_info)
        self.label_current_quantity.setObjectName("label_current_quantity")
        self.verticalLayout.addWidget(self.label_current_quantity)
        self.horizontalLayout.addWidget(self.frame_maim_info)
        self.pushButton_functional = QtWidgets.QPushButton(self.frame_book)
        self.pushButton_functional.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_functional.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_functional.setIcon(icon)
        self.pushButton_functional.setIconSize(QtCore.QSize(28, 32))
        self.pushButton_functional.setAutoDefault(False)
        self.pushButton_functional.setObjectName("pushButton_functional")
        self.horizontalLayout.addWidget(self.pushButton_functional, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "Название"))
        self.label_author.setText(_translate("Form", "Автор"))
        self.label_isbn.setText(_translate("Form", "ISBN"))
        self.label_year_publication.setText(_translate("Form", "Год  издания"))
        self.label_all_quantity.setText(_translate("Form", "Общее количество"))
        self.label_current_quantity.setText(_translate("Form", "Текущее количество экземпляров"))
        self.pushButton_functional.setText(_translate("Form", "Взаимодействие"))
import icons_rc
