# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\book\book-gived.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 170)
        Form.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame_zxc = QtWidgets.QFrame(Form)
        self.frame_zxc.setGeometry(QtCore.QRect(20, 10, 381, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_zxc.sizePolicy().hasHeightForWidth())
        self.frame_zxc.setSizePolicy(sizePolicy)
        self.frame_zxc.setMinimumSize(QtCore.QSize(321, 141))
        self.frame_zxc.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_zxc.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_zxc.setObjectName("frame_zxc")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_zxc)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_name = QtWidgets.QLabel(self.frame_zxc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_year_publication = QtWidgets.QLabel(self.frame_zxc)
        self.label_year_publication.setObjectName("label_year_publication")
        self.gridLayout.addWidget(self.label_year_publication, 3, 0, 1, 1)
        self.label_author = QtWidgets.QLabel(self.frame_zxc)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 0, 1, 1)
        self.label_isbn = QtWidgets.QLabel(self.frame_zxc)
        self.label_isbn.setObjectName("label_isbn")
        self.gridLayout.addWidget(self.label_isbn, 2, 0, 1, 1)
        self.label_date_take = QtWidgets.QLabel(self.frame_zxc)
        self.label_date_take.setObjectName("label_date_take")
        self.gridLayout.addWidget(self.label_date_take, 4, 0, 1, 1)
        self.pushButton_accept = QtWidgets.QPushButton(self.frame_zxc)
        self.pushButton_accept.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/book/book-pick-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_accept.setIcon(icon)
        self.pushButton_accept.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout.addWidget(self.pushButton_accept, 0, 1, 5, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "Название"))
        self.label_year_publication.setText(_translate("Form", "Год  издания"))
        self.label_author.setText(_translate("Form", "Автор"))
        self.label_isbn.setText(_translate("Form", "ISBN"))
        self.label_date_take.setText(_translate("Form", "Дата взятие книги"))
        self.pushButton_accept.setText(_translate("Form", "Принять книгу"))
import icons_rc
