# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\book\books.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 196)
        Form.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame_book = QtWidgets.QFrame(Form)
        self.frame_book.setGeometry(QtCore.QRect(20, 20, 391, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_book.sizePolicy().hasHeightForWidth())
        self.frame_book.setSizePolicy(sizePolicy)
        self.frame_book.setMinimumSize(QtCore.QSize(321, 141))
        self.frame_book.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_book.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_book.setObjectName("frame_book")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_book)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_name = QtWidgets.QLabel(self.frame_book)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)
        self.label_current_quantity = QtWidgets.QLabel(self.frame_book)
        self.label_current_quantity.setObjectName("label_current_quantity")
        self.gridLayout.addWidget(self.label_current_quantity, 5, 0, 1, 1)
        self.label_year_publication = QtWidgets.QLabel(self.frame_book)
        self.label_year_publication.setObjectName("label_year_publication")
        self.gridLayout.addWidget(self.label_year_publication, 3, 0, 1, 1)
        self.label_all_quantity = QtWidgets.QLabel(self.frame_book)
        self.label_all_quantity.setObjectName("label_all_quantity")
        self.gridLayout.addWidget(self.label_all_quantity, 4, 0, 1, 1)
        self.label_author = QtWidgets.QLabel(self.frame_book)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 0, 1, 1)
        self.label_isbn = QtWidgets.QLabel(self.frame_book)
        self.label_isbn.setObjectName("label_isbn")
        self.gridLayout.addWidget(self.label_isbn, 2, 0, 1, 1)
        self.frame_button = QtWidgets.QFrame(self.frame_book)
        self.frame_button.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_button)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_accept.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/book/book-pick-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_accept.setIcon(icon)
        self.pushButton_accept.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.verticalLayout.addWidget(self.pushButton_accept)
        self.pushButton_issue = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_issue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/book/book-gived.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_issue.setIcon(icon1)
        self.pushButton_issue.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_issue.setObjectName("pushButton_issue")
        self.verticalLayout.addWidget(self.pushButton_issue)
        self.pushButton_edit = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/book/edit-book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_edit.setIcon(icon2)
        self.pushButton_edit.setIconSize(QtCore.QSize(29, 29))
        self.pushButton_edit.setObjectName("pushButton_edit")
        self.verticalLayout.addWidget(self.pushButton_edit)
        self.gridLayout.addWidget(self.frame_button, 0, 1, 6, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_name.setText(_translate("Form", "Название"))
        self.label_current_quantity.setText(_translate("Form", "Текущее количество экземпляров"))
        self.label_year_publication.setText(_translate("Form", "Год  издания"))
        self.label_all_quantity.setText(_translate("Form", "Общее количество"))
        self.label_author.setText(_translate("Form", "Автор"))
        self.label_isbn.setText(_translate("Form", "ISBN"))
        self.pushButton_accept.setText(_translate("Form", "Принять книгу"))
        self.pushButton_issue.setText(_translate("Form", "Выдать книгу"))
        self.pushButton_edit.setText(_translate("Form", "Изменить данные"))
import icons_rc
