# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Project\Python\diplom\ui_file\element\book\history-book.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(413, 185)
        Form.setStyleSheet("QFrame {\n"
"    border: 1px solid black;\n"
"}")
        self.frame_book_history = QtWidgets.QFrame(Form)
        self.frame_book_history.setGeometry(QtCore.QRect(10, 20, 381, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_book_history.sizePolicy().hasHeightForWidth())
        self.frame_book_history.setSizePolicy(sizePolicy)
        self.frame_book_history.setMinimumSize(QtCore.QSize(321, 141))
        self.frame_book_history.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_book_history.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_book_history.setObjectName("frame_book_history")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_book_history)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.frame_book_history)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_date_take = QtWidgets.QLabel(self.frame)
        self.label_date_take.setObjectName("label_date_take")
        self.horizontalLayout.addWidget(self.label_date_take)
        self.label_date_return = QtWidgets.QLabel(self.frame)
        self.label_date_return.setObjectName("label_date_return")
        self.horizontalLayout.addWidget(self.label_date_return)
        self.gridLayout.addWidget(self.frame, 4, 0, 1, 1)
        self.label_author = QtWidgets.QLabel(self.frame_book_history)
        self.label_author.setObjectName("label_author")
        self.gridLayout.addWidget(self.label_author, 1, 0, 1, 1)
        self.label_isbn = QtWidgets.QLabel(self.frame_book_history)
        self.label_isbn.setObjectName("label_isbn")
        self.gridLayout.addWidget(self.label_isbn, 2, 0, 1, 1)
        self.label_year_publication = QtWidgets.QLabel(self.frame_book_history)
        self.label_year_publication.setObjectName("label_year_publication")
        self.gridLayout.addWidget(self.label_year_publication, 3, 0, 1, 1)
        self.label_name = QtWidgets.QLabel(self.frame_book_history)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_date_take.setText(_translate("Form", "label_date_take"))
        self.label_date_return.setText(_translate("Form", "label_date_return"))
        self.label_author.setText(_translate("Form", "Автор"))
        self.label_isbn.setText(_translate("Form", "ISBN"))
        self.label_year_publication.setText(_translate("Form", "Год  издания"))
        self.label_name.setText(_translate("Form", "Название"))
import icons_rc
